# Generated by Django 6.0.6 on 2026-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
