# Generated by Django 6.0.6 on 2026-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female')], max_length=10)),
                ('city', models.CharField(choices=[('hmt', 'himmatnagar'), ('idar', 'idar'), ('surat', 'surat')], max_length=10)),
            ],
        ),
    ]
